#!/usr/bin/env python3
"""
Orchestrator - Bronze Tier

Master process that coordinates the AI Employee components.

Features:
- Monitors Needs_Action folder
- Triggers Claude Code processing
- Updates dashboard
- Logs all activities

Usage:
    python orchestrator.py --vault /path/to/vault [--watch] [--process-now]
"""

import argparse
import json
import logging
import subprocess
import time
from pathlib import Path
from datetime import datetime
import sys

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler('orchestrator.log'),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)


class Orchestrator:
    """Coordinates AI Employee operations."""

    def __init__(self, vault_path: str):
        """
        Initialize orchestrator.

        Args:
            vault_path: Path to the Obsidian vault
        """
        self.vault_path = Path(vault_path).resolve()
        self.needs_action = self.vault_path / 'Needs_Action'
        self.plans = self.vault_path / 'Plans'
        self.done = self.vault_path / 'Done'
        self.logs = self.vault_path / 'Logs'
        self.dashboard = self.vault_path / 'Dashboard.md'

        # Ensure directories exist
        for folder in [self.plans, self.done, self.logs]:
            folder.mkdir(parents=True, exist_ok=True)

        logger.info(f"Orchestrator initialized with vault: {self.vault_path}")

    def check_needs_action(self) -> list:
        """
        Check for pending action items.

        Returns:
            List of Path objects for files in Needs_Action
        """
        if not self.needs_action.exists():
            return []

        items = list(self.needs_action.glob('*.md'))
        logger.info(f"Found {len(items)} items in Needs_Action")
        return items

    def log_action(self, action: dict):
        """
        Log an action to the daily log file.

        Args:
            action: Dictionary with action details
        """
        today = datetime.now().strftime('%Y-%m-%d')
        log_file = self.logs / f'{today}.json'

        # Load existing logs
        if log_file.exists():
            try:
                logs = json.loads(log_file.read_text())
            except json.JSONDecodeError:
                logs = []
        else:
            logs = []

        # Add timestamp
        action['timestamp'] = datetime.now().isoformat()
        logs.append(action)

        # Write back
        log_file.write_text(json.dumps(logs, indent=2))
        logger.debug(f"Logged action to {log_file}")

    def update_dashboard_stats(self):
        """Update dashboard with current statistics."""
        try:
            if not self.dashboard.exists():
                logger.warning("Dashboard.md not found, skipping update")
                return

            content = self.dashboard.read_text()

            # Count items
            needs_action_count = len(list(self.needs_action.glob('*.md'))) if self.needs_action.exists() else 0
            plans_count = len(list(self.plans.glob('*.md'))) if self.plans.exists() else 0
            done_count = len(list(self.done.glob('*.md'))) if self.done.exists() else 0

            # Simple update - replace placeholder values
            # In production, you'd parse and update properly
            logger.info(f"Stats: Needs_Action={needs_action_count}, Plans={plans_count}, Done={done_count}")

        except Exception as e:
            logger.error(f"Failed to update dashboard: {e}")

    def trigger_claude(self, item_path: Path) -> bool:
        """
        Trigger Claude Code to process an item.

        Args:
            item_path: Path to the action item

        Returns:
            True if successful, False otherwise
        """
        try:
            # For Bronze tier, we'll just create a simple plan
            # In Silver/Gold, this would invoke Claude Code programmatically

            plan_id = f"PLAN_{item_path.stem}_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
            plan_path = self.plans / f"{plan_id}.md"

            # Create a basic plan (what Claude would do)
            content = f"""---
plan_id: {plan_id}
created: {datetime.now().isoformat()}
source: {item_path.name}
status: in_progress
---

# Execution Plan

**From**: {item_path.name}
**Created**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Objective
Process the pending action item and move to completion.

## Steps

- [x] Read and analyze the source file
- [ ] Determine required actions
- [ ] Execute necessary file operations
- [ ] Update related records
- [ ] Move to Done folder
- [ ] Update Dashboard

## Notes
This plan was auto-generated by the orchestrator. Claude Code will execute these steps.

---

*Orchestrator v0.1-Bronze*
"""

            plan_path.write_text(content)
            logger.info(f"Created plan: {plan_path}")

            # Log the action
            self.log_action({
                'action_type': 'plan_created',
                'source_file': item_path.name,
                'plan_file': plan_path.name,
                'orchestrator': 'bronze-tier'
            })

            # Simulate completion (move item to done)
            done_path = self.done / item_path.name
            item_path.rename(done_path)

            logger.info(f"Moved {item_path.name} to Done")

            self.log_action({
                'action_type': 'task_completed',
                'source_file': item_path.name,
                'destination': str(done_path.relative_to(self.vault_path))
            })

            return True

        except Exception as e:
            logger.error(f"Failed to process {item_path}: {e}")
            return False

    def run_once(self) -> int:
        """
        Run one iteration of the orchestrator.

        Returns:
            Number of items processed
        """
        logger.info("Starting orchestrator iteration...")

        items = self.check_needs_action()
        processed = 0

        for item in items:
            logger.info(f"Processing: {item.name}")
            if self.trigger_claude(item):
                processed += 1
                logger.info(f"✓ Processed {item.name}")
            else:
                logger.error(f"✗ Failed to process {item.name}")

        # Update dashboard
        self.update_dashboard_stats()

        logger.info(f"Iteration complete. Processed {processed}/{len(items)} items.")
        return processed

    def watch(self, interval: int = 5):
        """
        Run in continuous watch mode.

        Args:
            interval: Check interval in seconds
        """
        logger.info(f"Starting watch mode (interval: {interval}s)")
        logger.info("Press Ctrl+C to stop")

        try:
            while True:
                self.run_once()
                time.sleep(interval)
        except KeyboardInterrupt:
            logger.info("Stopping orchestrator...")
        except Exception as e:
            logger.error(f"Orchestrator crashed: {e}")
            raise


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Orchestrator for AI Employee"
    )
    parser.add_argument(
        '--vault',
        required=True,
        help='Path to the Obsidian vault'
    )
    parser.add_argument(
        '--watch',
        action='store_true',
        help='Run in continuous watch mode'
    )
    parser.add_argument(
        '--interval',
        type=int,
        default=5,
        help='Check interval in seconds (watch mode only)'
    )
    parser.add_argument(
        '--process-now',
        action='store_true',
        help='Process pending items once and exit'
    )

    args = parser.parse_args()

    vault_path = Path(args.vault).resolve()

    if not vault_path.exists():
        logger.error(f"Vault path does not exist: {vault_path}")
        return 1

    orchestrator = Orchestrator(str(vault_path))

    if args.watch:
        orchestrator.watch(interval=args.interval)
    else:
        # Default: process once
        processed = orchestrator.run_once()
        print(f"\n✅ Processed {processed} items")
        print(f"📁 Vault: {vault_path}")
        print(f"📊 Check Dashboard.md for status")

    return 0


if __name__ == "__main__":
    exit(main())
